### ISSUE TITLE
setka

### ISSUE THREAD

**Issue by wmdhosting** [spicywebau/craft-tinymce#1]
Hey :)  Tinymce is great addition..  
Thx

Any plan on creating plugin for this.. 
https://setka.io/

**Comment by ttempleton** [comment]
Glad you're enjoying the TinyMCE plugin! 🙂

Unfortunately it seems that the [Setka editor is being phased out](https://www.tiny.cloud/blog/sunsetting-setka-editor/), so at this point we have no plans to work on a plugin for it. Definitely happy to consider other editor plugin requests, though!
