### ISSUE TITLE
Fresh Install throws Invalid `tinymceSource` setting set error

### ISSUE THREAD

**Issue by mjniland1** [spicywebau/craft-tinymce#11]
### Bug Description

Upon the initial installation of the plugin, the following error is presented to the user:

`Invalid TinyMCE source – spicyweb\tinymce\errors\InvalidSourceException
Invalid tinymceSource setting set.`

However, when the user navigates to /admin/settings/plugins/tinymce and clicks on the save button, even without making any changes to the default settings, the error is resolved.

### Steps to reproduce

1. Install TinyMCE
2. Create a TinyMCE custom field
3. Add that field to an entry 
4. View the entry in the CP, you should see the error listed above. 
5. Saving the plugin settings for TinyMCE clears the error. 

### TinyMCE Field version

1.4.1

### Craft CMS version

4.5.9

**Comment by ttempleton** [comment]
Thanks for reporting that - fixed now in 1.4.2.
