### ISSUE TITLE
Content is hidden after changing the order of Neo blocks

### ISSUE THREAD

**Issue by mjniland1** [spicywebau/craft-tinymce#12]
### Bug Description

I have a Neo block layout that contains a TinyMCE field. If I click and drag the Neo block that contains the Tiny MCE field, the content of the Tiny MCE field disappears. The content is visible again on page save/reload. 

https://github.com/spicywebau/craft-tinymce/assets/56364768/c53cd85a-55d3-40a6-92c5-b20309c7ebd2

### Steps to reproduce

1. Add a Tiny MCE field to a Neo block layout
2. On an entry, click and drag the Neo block containing the Tiny MCE field
3. The content of the Tiny MCE field will disappear and won't be visible again until the user saves/reloads the page.

### Expected behaviour

The content should be visible after reordering the Neo blocks. 

### TinyMCE Field version

1.4.1

### Craft CMS version

4.5.9

**Comment by ttempleton** [comment]
Thanks for reporting that - it seems to affect TinyMCE fields in Matrix blocks as well (and I haven't tested in Super Table but I'd expect that case to also be affected). Not entirely sure what's causing it but will keep looking into it.

**Comment by ttempleton** [comment]
This should be fixed now in 1.4.3.

Please note that with 1.4.3, a TinyMCE field's content will still disappear while dragging the blocks; I think this is due to Craft cloning the dragged block before triggering the event we need to listen for. When you finish dragging the block, though, the content should reappear. Please let me know if the issue persists for you, though.

**Comment by ttempleton** [comment]
I've just released 1.4.4 with a fix for the content not showing while the block is being dragged. Now there might be a slight flicker of the content while we insert it into the cloned iframe, but the content should otherwise appear as normal while dragging the block.

**Comment by mjniland1** [comment]
This worked for me but only after I reenabled the `autoresize` TinyMCE plugin in the .json config file. Thanks for the fix!
