### ISSUE TITLE
link_class_list doesn't save 100% of the time

### ISSUE THREAD

**Issue by mjniland1** [spicywebau/craft-tinymce#13]
### Bug Description

I'm using link_class_list within my tinyMce .json file to add style classes to my links. I've noticed that more often than not, when I apply a link class, the change doesn't save. Its only after I continue typing within the Mce field that the changes are stored. I added save & autosave to my plugin index but the behavior remains the same. 

https://github.com/spicywebau/craft-tinymce/assets/56364768/a727322a-2fcc-4347-95b0-7b29c9cc588b

### Steps to reproduce

1. Add a link class to the .json file e.g 
`"link_class_list": [
		{
		 	"title": "Styles",
		 	"menu": [
				{ "title": "Default Button", "value": "button" }
		 	]
		}
	]`
2. Apply that link class to a link within the mce field and save the entry.
3. The link class will be removed on save. 

### Expected behaviour

The link class should be saved on entry save. 

### TinyMCE Field version

1.4.8

### Craft CMS version

Craft Pro 4.7.1

**Comment by ttempleton** [comment]
Thanks for reporting this - it turned out that we weren't picking up the change in the editor to trigger a draft autosave. Fixed now in 1.4.9.
