### ISSUE TITLE
Neo + Anchor Tag

### ISSUE THREAD

**Issue by mjniland1** [spicywebau/craft-tinymce#14]
### Bug Description

Neo appears to override link href hash values when I attempt to link to an anchor on a page. E.g. Setting a href of `#anchor-test` on save will result in a href like this: `#fields-neo-blocks-7790-fields-anchor-test`.

https://github.com/spicywebau/craft-tinymce/assets/56364768/d273064d-8030-47d9-a93a-2599155a66a2

### Steps to reproduce

1. Create a Neo field that contains a Tiny MCE field and add it to an entry
2. On the entry, create a new block and add a hash only link to the Tiny MCE field 
3. On save, the hash value will be overwritten. 

### Expected behaviour

The hash value should stay the same. 

### TinyMCE Field version

1.4.9

### Craft CMS version

4.7.2.1

**Comment by ttempleton** [comment]
Thanks for reporting this - it turned out to also affect TinyMCE fields in Matrix blocks, and is now fixed in 1.4.10.
