### ISSUE TITLE
Custom config

### ISSUE THREAD

**Issue by wmdhosting** [spicywebau/craft-tinymce#2]
I tryed to build custom config.  but getting wired results.. 

Any chance to include by install.     full config.. too >>  as on their page.. 
https://www.tiny.cloud/docs/tinymce/6/full-featured-open-source-demo/

Its eaiser to remove things than to build from scracth :)

And that will save much time to people and will be more plugin installs..
No brainer best  editor for end user..

**Comment by wmdhosting** [comment]
Just . info.  i got some better looking version..   but assets and links  opens..  TinyMCE thing, not one you integrated in craft..
And dont know how to get this 3 dots..  for more icons..  at the end of first row..

`{
    
  "toolbar": [
      "undo redo | bold italic underline strikethrough | fontfamily fontsize blocks | table alignleft aligncenter alignright alignjustify | outdent indent |  numlist bullist | forecolor backcolor removeformat | pagebreak  | charmap emoticons | fullscreen  preview save print | insertfile image media template link anchor codesample | ltr rtl"
  ],
  "plugins": [
    "preview","table","importcss","searchreplace","autolink","autosave","save","directionality","code","visualblocks","visualchars","fullscreen","image","link","media","template","codesample","table","charmap","pagebreak","nonbreaking","anchor","insertdatetime","advlist","lists","wordcount","help","charmap","quickbars","emoticons"
  ],
 "menubar": [ 
     "file edit view insert format tools table"
     ],
     

     
     "toolbar_mode": "sliding",
 "quickbars_selection_toolbar": "bold italic | quicklink h2 h3 blockquote quickimage tablecellprops quicktable ",
 "contextmenu": "link image table",
 "selector": "textarea#open-source-plugins"
}
`

**Comment by ttempleton** [comment]
To get the plugin's link to Craft element / insert Craft image asset options:

- In `"toolbar"`, replace `link` with `insertLink`, and `image` with `insertImage`
- In `"contextmenu"`, replace `link` with `craftLink`, and `image` with `craftImage`

Regarding your feature request, I'm working on a solution that will generate default, simple, and full config files when installing the plugin and allow regenerating them using console commands, and will give the console commands the ability to override certain settings in the generated file.

**Comment by wmdhosting** [comment]
ok great :)  thx

**Comment by ttempleton** [comment]
I've just released version 1.1.0 with the above-mentioned config file generation when installing the plugin, and with [console commands](https://github.com/spicywebau/craft-tinymce/blob/f1f5caed708a6b24cf36ca6fedf14f08709a16a0/docs/console-commands.md).

**Comment by wmdhosting** [comment]
OK great thx :) 

All work OK.  
I think you will get more installs if add one more image   on plugin page.. of Full toolbar.. 
Somethign like this.. 
![Snag_b6b30f9](https://user-images.githubusercontent.com/76176291/194755540-5c129c9f-7459-43cb-9fd2-45859d46b1d7.png)

**Comment by gracehcoote** [comment]
> To get the plugin's link to Craft element / insert Craft image asset options:
> 
> * In `"toolbar"`, replace `link` with `insertLink`, and `image` with `insertImage`
> * In `"contextmenu"`, replace `link` with `craftLink`, and `image` with `craftImage`

Just to jump on the back of this two years later, I am finding that when I use the Craftlink functionality and link to an entry, the URL is getting extra content appended to it, e.g. linking to the 'About' entry, the link becomes "about#entry:2@1url". Any ideas how to prevent that from happening?

**Comment by ttempleton** [comment]
@gracehcoote Is that appearing on the front-end link? It's normal for extra content to be appended to what's saved for the field, so Craft can still keep track of the linked entry e.g. if the entry's URL changes in the future, but it definitely should not appear on the front-end link.

**Comment by gracehcoote** [comment]
@ttempleton Yes that's correct, the appended link is visible on the frontend. I've attached a screenshot to show what appears when you hover the link. 

<img width="1015" alt="Screenshot 2024-11-19 at 09 51 29" src="https://github.com/user-attachments/assets/587cd710-b3fb-480a-9234-577e11188e05">

**Comment by gracehcoote** [comment]
@ttempleton Apologies, just realised the screenshot never uploaded. You should be able to see it now, on the bottom left you'll see what the link is showing on hover.

**Comment by ttempleton** [comment]
Thanks for confirming that. There should be a `:` between the `1` and `url`, i.e. the extra content in the case shown in the screenshot should be `#entry:2@1:url`. Adding the `:` in should fix that link, but if that keeps happening with new links, please let me know and I'll split this into a new bug report.
