### ISSUE TITLE
Matrix issue

### ISSUE THREAD

**Issue by wmdhosting** [spicywebau/craft-tinymce#4]
I have latest verision of all.  Craft and TinyMCE

tested on upgraded craft and fresh craft installl. 

ON both .   when i create or change field to Tinymce 
It creates in all existing matrix field. some additonl setting fields. 

More field you have more this field is created..    
![Snag_bc3d00c](https://user-images.githubusercontent.com/76176291/197763632-8514daa2-0b63-416e-b304-54234913543a.png)

**Comment by ttempleton** [comment]
I'm unable to reproduce this so far.

- Are there any JavaScript errors in the browser console?
- Are there any issues with any other field types (especially Redactor) in a Matrix field?
- If no to both of the above, could you please provide detailed steps to reproduce this from a fresh Craft install, in case there's something I'm missing?

**Comment by wmdhosting** [comment]
I tryed again. creating new filed with multiple block. 

Seems when 1  block. then OK... 
but when you have multiple  block then issue.. 

Allready on second.. 

i get this error. when i try to save...new tiny field..
![Snag_c0f670f](https://user-images.githubusercontent.com/76176291/197779564-abc53644-0de2-4a0f-9910-de79b36851bf.png)

**Comment by ttempleton** [comment]
Does everything work as expected if you do the same thing with a Redactor field instead of a TinyMCE field?

**Comment by wmdhosting** [comment]
i created similar new matrix with redactor all OK:. 

Then i tryed to change existign  to redactor fields. 
But still getting  same error as above..  on that first field ..  even i didnt choosen Tinymce..

**Comment by ttempleton** [comment]
Are there any JavaScript errors in the browser console when it happens? If so, could you please paste them in here or take a screenshot of them?

**Comment by wmdhosting** [comment]
NO..   but few screenshots.. 

After 1 field .. it change css for craft native fileds.. 
After 2 more..  changes.. 
![Snag_c60d0fa](https://user-images.githubusercontent.com/76176291/197801469-195aea93-a5ea-4951-b322-05abb535ba1c.png)

![Snag_c60e5cb](https://user-images.githubusercontent.com/76176291/197801493-32b47c43-bf7f-4055-9ea0-f3c19637619c.png)
![Snag_c60f74f](https://user-images.githubusercontent.com/76176291/197801512-77fc6044-e351-42c2-a4d8-7a8befc05b17.png)

![Snag_c6105f5](https://user-images.githubusercontent.com/76176291/197801530-7a8fa1de-0db7-416f-b890-410464dfe67d.png)

**Comment by wmdhosting** [comment]
gettings only this error. in normal field.  .. not matrix..
![Snag_c69aef0](https://user-images.githubusercontent.com/76176291/197803938-45943ec2-0fbf-4c45-b663-016722a97a6a.png)

**Comment by ttempleton** [comment]
This should be fixed now in TinyMCE Field 1.1.1 - it turned out that I missed a `</div>` in the field settings template 😅
