### ISSUE TITLE
Not showing content in preview.. 

### ISSUE THREAD

**Issue by wmdhosting** [spicywebau/craft-tinymce#6]
### Bug Description

![Snag_1728a825](https://user-images.githubusercontent.com/76176291/198349840-61f8e415-6e7b-425d-b884-080506917ef6.png)
Then preview

![Snag_1728be0e](https://user-images.githubusercontent.com/76176291/198349856-826b5316-0528-423e-8640-855c19e1555d.png)

then back
![Snag_1728faaa](https://user-images.githubusercontent.com/76176291/198349922-c05f6a4e-fe7d-45aa-9bc5-23104a3181ac.png)

### Steps to reproduce

same thing in normal field and when in matrix.. 
![Snag_1729f6ad](https://user-images.githubusercontent.com/76176291/198350129-b4e74267-102a-4d0d-8745-da2739d9d9fc.png)

### TinyMCE Field version

1.2.0

### Craft CMS version

4.3

**Comment by ttempleton** [comment]
Thanks for reporting that - fixed now in 1.2.1.
