### ISSUE TITLE
embed code.

### ISSUE THREAD

**Issue by wmdhosting** [spicywebau/craft-tinymce#7]
### What question would you like to ask?

Hey :)

Trying to add embed code.  liek this. below
tryed in all ways. but does not work..   
in redactor. i do that by widget.. icon..

I remove HTML purifier.. and all other settings.  but still same. 
Whatever i addit. by  embed. code.  source code.. 

Any idea. thx

`<a href="https://dev.zpubbz.hr/izvjezce-2009-2013/" class="fbp-embed" data-fbp-ratio="3:2" data-fbp-lightbox="no" data-fbp-width="100%" data-fbp-height="auto"></a><script async="" defer="" src="https://dev.zpubbz.hr/izvjezce-2009-2013/files/html/static/embed.js"></script>`

**Comment by ttempleton** [comment]
Regarding the `<a>` tag, TinyMCE is removing that because it has no content. Adding something like a space will get it to stay there.

Regarding the `<script>` tag - it is ***very strongly discouraged*** to do this, and it would be much better to use a [Matrix-based](https://craftcms.stackexchange.com/a/12059) or [plain text-based](https://craftcms.stackexchange.com/a/10348) solution, if any part of the `<script>` tag needs to be editable by a content author at all.

If you still want to allow `<script>` tags in TinyMCE fields, [this](https://www.tiny.cloud/docs/tinymce/6/content-filtering/#using-extended_valid_elements-to-allow-script-elements) is how you would do it. **Please note the warning on that page about XSS attacks, and be aware that we are not responsible for any harm done as a result of you using that configuration option.**

Please let me know if you have any additional questions!

**Comment by wmdhosting** [comment]
ok thx..  for quick answer. 

I tryed  ..  with Embedded Assets from url

It saves json from  .. but does nto show it. 
Can i extend.. it  to support this files.. 
As its from. ..  https://flippingbook.com/

**Comment by ttempleton** [comment]
Embedded Assets doesn't ([and won't](https://github.com/spicywebau/craft-embedded-assets/issues/7)) support rich text fields, sorry.

**Comment by wmdhosting** [comment]
i didnt mean that..   

I put  this url https://dev.zpubbz.hr/izvjezce-2009-2013/  
And there is preview  Json is created.. 

I just asked is it posiblle to  extend it. to show..  that in template..

**Comment by ttempleton** [comment]
Sorry, I'm a bit confused; what is it that you're trying to do with embedded asset JSON and TinyMCE fields?

**Comment by wmdhosting** [comment]
Sorry for misunderstanding, didnt wanted to open another new  ticket on other plugin.. for same thing

![Snag_5be4538](https://user-images.githubusercontent.com/76176291/201276313-1e78a1b1-9b0c-40b2-bcb8-7bedfe10c378.png)

Can i extend  Embeded assets plugin.  so i show this type.. of content..  FLIPbook.. too..

**Comment by ttempleton** [comment]
Ahh, okay. Just wondering, is that still coming up as a "Rich" type of asset for you? For me it's coming up as "Link".

Either way, the first step you'll need to take is to add the website to the plugin's whitelist, by creating a `config/embeddedassets.php` file with the following (or adding the `extraWhitelist` setting if the file already exists):

```php
<?php

return [
    'extraWhitelist' => [
	'zpubbz.hr',
    ],
];
```

**Comment by wmdhosting** [comment]
Seems it turned as "Rich"  becuse i have iframely..  turned on. .
When ifamely turned off i get  Link too...  
-------------------------------------------------------
it works same with config or without..

When Link  **code** part in json is null.. 

with iframely.. Rich > this below

`<div class=\"iframely-embed\"><div class=\"iframely-responsive\" style=\"padding-bottom: 52.5%; padding-top: 120px;\"><a href=\"https://dev.zpubbz.hr/izvjezce-2009-2013/\" data-iframely-url=\"//cdn.iframe.ly/api/iframe?maxheight=1080&url=https%3A%2F%2Fdev.zpubbz.hr%2Fizvjezce-2009-2013%2F&key=9fc12ef43c40dea7481b39e821f7d224\"></a></div></div><script async src=\"//cdn.iframe.ly/embed.js\" charset=\"utf-8\"></script>`

**Comment by ttempleton** [comment]
I've just tried that URL with the [Iframely test page](https://iframely.com/try?url=https%3A%2F%2Fdev.zpubbz.hr%2Fizvjezce-2009-2013%2F), and it looks like we're getting no better than what Embedded Assets would give you without Iframely involved. I'll need to add a new provider so Embedded Assets is compatible with that site. Could you please open a [new feature request with Embedded Assets](https://github.com/spicywebau/craft-embedded-assets/issues/new/choose) for this, just so the information is over there (feel free to link back to this issue) and I should be able to work on it either late this week or early next week.
