### ISSUE TITLE
Have setting for TinyMCE API key for premium plugins under cloud paid accounts

### ISSUE THREAD

**Issue by zizther** [spicywebau/craft-tinymce#8]
### What would you like to see added to or changed in TinyMCE Field, and why?

It would be good to have a setting for Tiny Cloud or Self hosted Cloud premium setups to be able to enable Tiny premium plugins.

I don't know if this would adjust the JS being added in or would have another option if an API key was added.
I have output examples of the scripts in the Tiny docs.

**Cloud integration**
`https://cdn.tiny.cloud/1/<API_KEY>/tinymce/6/tinymce.min.js`

**Self-hosted + Cloud Premium Deployment**
Hosted file:
`https://<hostname.tld>/tinymce.min.js`

Tiny Premium Plugins:
`https://cdn.tiny.cloud/1/<API_KEY>/tinymce/6/plugins.min.js`

**Comment by ttempleton** [comment]
There was previously an `editorCloudApiKey` plugin setting, but it wasn't documented and had various issues. It should now be working in 1.3.0.

1.3.0 also adds the `enablePremiumPlugins` setting. Please note that I'm not currently able to test that premium plugins work and have only been able to verify that `plugins.min.js` is being loaded, so please do let me know if you have success with it.

**Comment by zizther** [comment]
🌟 I will test this out and report any issues if I come across them
