### ISSUE TITLE
Setting/Config control for TinyMCE version

### ISSUE THREAD

**Issue by zizther** [spicywebau/craft-tinymce#9]
### What would you like to see added to or changed in TinyMCE Field, and why?

Would it be possible to have control over the version of TinyMCE that is used? This could be a setting that allows users to enter a URL in the CP settings page and config file, allowing it to load from a server or external source like JS Delivr, or it could fall back if left empty which would fallback to the version provided in the plugin.

By doing this, the user would be able to choose their own TinyMCE version rather than having it determined by a plugin.

There may be a connection between this and #8 where users have the ability to enter the URL for their version of TinyMCE and Tiny Cloud premium plugin

This could be related to https://github.com/spicywebau/craft-tinymce/issues/8 where entering a URL for TinyMCE and the Tiny Cloud premium plugins URL along with an API key, these option of these 2 fields give the flexibility for both this and #8

**Comment by zizther** [comment]
Is there any progress on supporting the latest of different versions of TinyMCE and related plugins.
I am unable to use the `paste` plugin as it is not supported within this plugin.

Offering greater control over resources would mean it is not held up by the version of the plugin

**Comment by ttempleton** [comment]
I haven't looked at TinyMCE 5 support yet, but I'm planning to wrap up work on [another feature](https://github.com/spicywebau/craft-tinymce/pull/10) and make a new release in a couple of weeks when I have time, and I'm happy to look at this then.

**Comment by zizther** [comment]
Thanks @ttempleton 
We are using TinyMCE (v6, not v5) on the frontend of the site, which is where the entries are primarily being managed for this section, we are using TinyMCE 6.5.1 along with standard and premium plugins.
We are using this plugin to support the field within the Craft CP and want to match the same configs.

The latest I noticed was the paste functionality is managed through a plugin which is not support in this plugin yet. Specifically the `paste_word_valid_elements` option.
Having the option to manage the version of TinyMCE and plugin would fix to certain versions of TinyMCE and plugins without having to rely on the plugin.

**Comment by ttempleton** [comment]
According to the [TinyMCE docs](https://www.tiny.cloud/docs/plugins/opensource/paste/#paste_word_valid_elements), the `paste_word_valid_elements` option was removed in TinyMCE 6. Is that inaccurate?

**Comment by zizther** [comment]
@ttempleton This is correct, as we moved from TinyMCE v5 to v6 it no longer supports this due to moving the functionality within the paste plugin
https://www.tiny.cloud/docs-4x/plugins/paste/#paste_word_valid_elements

This plugin does not seem to be supported in the current version of craft-tinymce

This is a scenario related to having not having support for config controlled versions of TinyMCE and plugins

**Comment by ttempleton** [comment]
I've just released TinyMCE Field 1.4.0 with the [`tinymceSource`](https://github.com/spicywebau/craft-tinymce/blob/1.4.0/docs/plugin-settings.md#tinymcesource) and [`tinymceCustomSource`](https://github.com/spicywebau/craft-tinymce/blob/1.4.0/docs/plugin-settings.md#tinymcecustomsource) settings (editable either in a newly-added plugin settings page in the Craft control panel, or via `config/tinymce.php`), hopefully that resolves your issue.

**Comment by ttempleton** [comment]
Ahh whoops, I forgot about the custom plugin source.

**Comment by ttempleton** [comment]
I've just released 1.4.1, which allows premium plugins to be enabled when using a custom source for TinyMCE itself. Let me know if that works for you, or if you'd still prefer a custom text field so you can set a specific version.
